### PR TITLE
Energy Support, NLE Support and AP throttling and handling

### PR DESCRIPTION
**Pull request by tmenguy**
Hi, 

Here it is.

In fact the energy support is adding by nature (you need an API call by device) some API calls ... and this is why I had to rewrite the way of doing APIs call control with batches with a more predictable and controllable model, to get into the strict netatmo limits, and smooth and spread the calls too. 
So energy AND API control will have to go hand in hand unfortunately for the size of the PR ...

BR
Thomas

### CODE REVIEW

**Comment by tmenguy** [comment]
Great we will be able to rollout beta testing on this for those who want

**Comment by tmenguy** [comment]
Any list ? Or discord channel to have people test?

**Comment by chriscatuk** [comment]
I would be able to test it. But I might need some guidance on the best way to proceed. it would be my first beta testing.

I have a few Netatmo equipments that I would gladly add to the energy page.

**Comment by tmenguy** [comment]
great! would be very helpful, and you can reach to @cgtobi on Discord to join the discussion and report issues if any

**Comment by chriscatuk** [comment]
I will have to join Discord if it cannot be discussed here.
It seems the support for multi houses makes it so that it finds nothing. I have 5 of them, only 3 where something is left. 
For the moment I have 0 device found.

```
2024-08-30 18:01:48.552 DEBUG (MainThread) [custom_components.netatmo.pyatmo.helpers] Server response (tag: home): {'status': 'ok', 'time_server': 1725033709}
2024-08-30 18:01:48.552 DEBUG (MainThread) [custom_components.netatmo.data_handler] init account.async_update_status error NoDevice or ApiError No device found, errors in response
2024-08-30 18:01:48.553 INFO (MainThread) [custom_components.netatmo.data_handler] Netatmo integration not yet initialized, trying again in 60 seconds
2024-08-30 18:01:48.554 DEBUG (MainThread) [custom_components.netatmo.data_handler] Calls per hour: 1 , num call asked: 12 num candidates: 0 num call predicted : 0 num pub: 0
2024-08-30 18:01:55.347 DEBUG (MainThread) [custom_components.netatmo.pyatmo.auth] The Netatmo API returned b'{"error":{"code":7,"message":"Nothing to drop"}}' (406)
2024-08-30 18:01:55.347 DEBUG (MainThread) [custom_components.netatmo] No webhook to be dropped
2024-08-30 18:01:55.347 INFO (MainThread) [custom_components.netatmo] Unregister Netatmo webhook
```

**Pull request merged**
